name: pmultiqc
description: A library for proteomics QC report based on MultiQC framework.
keywords:
  - MultiQC
  - QC
  - Proteomics
tools:
  - pmultiqc:
      description: |
        A library for proteomics QC report based on MultiQC framework.
      homepage: https://github.com/bigbio/pmultiqc/
      documentation: https://github.com/bigbio/pmultiqc/
input:
  - expdesign:
      type: file
      description: experimental design file in openms style
  - mzmls:
      type: dir
      description: mzML files directory
  - quantms_results:
      type: dir
      description: the directory of quantms results including out.mzTab/out_msstats.csv
  - raw_ids:
      type: dir
      description: idXML files directory
output:
  - report:
      type: file
      description: MultiQC report file
      pattern: "multiqc_report.html"
  - quantmsdb:
      type: file
      description: Sqlite3 database file stored protein psm and quantificaiton information
      pattern: "*.db"
  - data:
      type: dir
      description: MultiQC data dir
      pattern: "multiqc_data"
  - plots:
      type: file
      description: Plots created by MultiQC
      pattern: "*_data"
  - version:
      type: file
      description: File containing software version
      pattern: "versions.yml"
authors:
  - "@Chengxin Dai"
