name: silicolibrarygeneration
description: A module for in silico predicted library generation based on DIA-NN.
keywords:
  - DIA-NN
  - library free
  - DIA
tools:
  - DIA-NN:
      description: |
        DIA-NN - a universal software for data-independent acquisition (DIA) proteomics data processing by Demichev.
      homepage: https://github.com/vdemichev/DiaNN
      documentation: https://github.com/vdemichev/DiaNN
input:
  - fasta:
      type: file
      description: FASTA sequence databases
      pattern: "*.{fasta,fa}"
  - cfg:
      type: file
      description: specifies a configuration file to load options/commands from.
      pattern: "*.cfg"
output:
  - predict_speclib:
      type: file
      description: Silico-predicted spectral library by deep leaning predictor in DIA-NN
      pattern: "*.predicted.speclib"
  - log:
      type: file
      description: DIA-NN log file
      pattern: "silicolibrarygeneration.log"
  - version:
      type: file
      description: File containing software version
      pattern: "versions.yml"
authors:
  - "@daichengxin"
