lint:
  files_exist:
    - conf/igenomes.config
    - conf/test_full.config
    - conf/test.config
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - .github/workflows/ci.yml
    - .github/workflows/download_pipeline.yml
    - .gitignore
  files_unchanged:
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/CONTRIBUTING.md
    - docs/README.md
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - .github/workflows/download_pipeline.yml
  included_configs: false
  multiqc_config: false
  nextflow_config: false
nf_core_version: 3.2.1
repository_type: pipeline
template:
  author: Yasset Perez-Riverol
  description: Quantitative Mass Spectrometry nf-core workflow
  force: false
  is_nfcore: true
  name: quantms
  org: bigbio
  outdir: .
  version: 1.4.1dev
