lint:
  files_exist:
    - conf/igenomes.config
    - conf/test_full.config
    - conf/test.config
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - .github/workflows/ci.yml
    - .gitignore
  files_unchanged:
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/CONTRIBUTING.md
    - docs/README.md
  multiqc_config: False
  nextflow_config: False
  included_configs: False
nf_core_version: 3.2.0
repository_type: pipeline
template:
  author: Yasset Perez-Riverol
  description: Quantitative Mass Spectrometry nf-core workflow
  force: false
  is_nfcore: true
  name: quantms
  org: bigbio
  outdir: .
  version: 1.4.0dev
