repository_type: pipeline
nf_core_version: "2.14.1"
lint:
  files_exist:
    - conf/igenomes.config
    - conf/test_full.config
    - conf/test.config
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  files_unchanged:
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/CONTRIBUTING.md
    - docs/README.md
  multiqc_config: False
