name: SAGEFEATURE
description: A module to extract extra features from ms2rescore
keywords:
  - features
  - ms2rescore
tools:
  - custom:
      description: |
        A custom module to extract extra features from ms2rescore.
      homepage: https://github.com/bigbio/quantms
      documentation: https://github.com/bigbio/quantms/tree/readthedocs
input:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - id_file:
      type: file
      description: |
        Input idXML file containing the identifications.
      pattern: "*.idXML"
output:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - id_files_feat:
      type: file
      description: |
        Output file in idXML format
      pattern: "*.idXML"
  - log:
      type: file
      description: log file
      pattern: "*.log"
  - version:
      type: file
      description: File containing software version
      pattern: "versions.yml"
authors:
  - "@daichengxin"
