name: MZMLSTATISTICS
description: A module for mzMLs statistics
keywords:
  - mzML
  - statistics
tools:
  - custom:
      description: |
        A custom module for mzMLs statistics.
      homepage: https://github.com/bigbio/quantms
      documentation: https://github.com/bigbio/quantms/tree/readthedocs
input:
  - mzmls:
      type: dir
      description: mzML files directory
output:
  - mzml_statistics:
      type: file
      description: mzMLs statistics file
      pattern: "mzml_info.tsv"
  - version:
      type: file
      description: File containing software version
      pattern: "versions.yml"
authors:
  - "@wanghong"
