name: diann_msstats
description: Convert DIA-NN report to MSstats format
keywords:
  - DIA-NN
  - conversion
  - MSstats
tools:
  - custom:
      description: |
        A custom module for DIA-NN report to MSstats conversion.
      homepage: https://github.com/bigbio/quantms
      documentation: https://github.com/bigbio/quantms/tree/readthedocs
input:
  - report:
      type: file
      description: DIA-NN main report file
      pattern: "*.tsv"
  - exp_design:
      type: file
      description: An experimental design file including Sample and replicates column et al.
      pattern: "*.tsv"
  - report_pr:
      type: file
      description: A text table containing normalized quantities for precursors. They are filtered at 1% FDR, using both global and run-specific q-values for precursors
      pattern: "*pr_matrix.tsv"
  - report_pg:
      type: file
      description: A text table containing normalized quantities for protein groups. They are filtered at 1% FDR, using global q-values for protein groups
      pattern: "*pg_matrix.tsv"
  - meta:
      type: map
      description: Groovy Map containing sample information
  - fasta:
      type: file
      description: Protein sequence database in Fasta format.
      pattern: "*.{fasta,fa}"
output:
  - out_msstats:
      type: file
      description: MSstats input file
      pattern: "*msstats_in.csv"
  - version:
      type: file
      description: File containing software version
      pattern: "versions.yml"
authors:
  - "@daichengxin"
  - "@wanghong"
