name: idpep
description: Tool to estimate the probability of peptide hits to be incorrectly assigned.
keywords:
  - PSM rescoring
  - decoy
  - OpenMS
tools:
  - IDPosteriorErrorProbability:
      description: |
        Tool to estimate the probability of peptide hits to be incorrectly assigned.
      homepage: https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/TOPP_IDPosteriorErrorProbability.html
      documentation: https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/TOPP_IDPosteriorErrorProbability.html
input:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - id_file:
      type: file
      description: |
        Peptide-spectrum matches annotated with target-decoy information.
      pattern: "*.idXML"
output:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - id_files_ForIDPEP:
      type: file
      description: |
        Identifications with annotated FDR.
      pattern: "*.idXML"
  - log:
      type: file
      description: log file
      pattern: "*.log"
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"
authors:
  - "@daichengxin"
