name: EXTRACTPSMFEATURES
description: Extracts PSM features from multiple search engines for rescoring.
keywords:
  - PSM
  - feature extraction
  - rescoring
  - OpenMS
tools:
  - PSMFeatureExtractor:
      description: |
        Tool to extract PSM features from identification results for downstream rescoring.
      homepage: https://abibuilder.cs.uni-tuebingen.de/archive/openms/Documentation/nightly/html/TOPP_PSMFeatureExtractor.html
      documentation: https://abibuilder.cs.uni-tuebingen.de/archive/openms/Documentation/nightly/html/TOPP_PSMFeatureExtractor.html
input:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - id_files:
      type: file
      description: |
        Identification files from one or multiple search engines.
      pattern: "*.idparquet"
output:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - id_files_feat:
      type: file
      description: |
        PSM features in Parquet format for rescoring.
      pattern: "*_feat.idparquet"
  - log:
      type: file
      description: log file
      pattern: "*.log"
  - version:
      type: file
      description: File containing software version
      pattern: "versions.yml"
authors:
  - "@daichengxin"
