contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #quantms channel"
    url: https://nfcore.slack.com/channels/quantms
    about: Discussion about the nf-core/quantms pipeline
