name: idripper
description: Splits the protein/peptide identifications of an idXML file into several idXML files according their annotated file origin.
keywords:
  - split
  - idXML
  - OpenMS
tools:
  - IDMerger:
      description: |
        IDRipper splits the protein/peptide identifications of an idXML file into several idXML files according their annotated file origin.
      homepage: https://www.openms.org/documentation/html/TOPP_IDRipper.html
      documentation: https://www.openms.org/documentation/html/TOPP_IDRipper.html
input:
  - id_file:
      type: file
      description: |
        Input file, in which the protein/peptide identifications must be tagged with 'file_origin'
      pattern: "*.{idXML}"
output:
  - id_rippers:
      type: file
      description: Output split files
      pattern: "*.{idXML}"
  - log:
      type: file
      description: log file
      pattern: "*.log"
  - version:
      type: file
      description: File containing software version
      pattern: "versions.yml"
authors:
  - "@daichengxin"
