name: thermorawfileparser
description: convert raw file to mzml files
keywords:
  - raw
  - mzML
  - OpenMS
tools:
  - thermorawfileparser:
      description: |
        It takes a thermo RAW file as input and outputs indexed mzML
      homepage: https://github.com/compomics/ThermoRawFileParser
      documentation: https://github.com/compomics/ThermoRawFileParser
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
  - rawfile:
      type: file
      description: |
        thermo RAW file
      pattern: "*.{raw,RAW}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'MD5', enzyme:trypsin ]
  - mzml:
      type: file
      description: indexed mzML
      pattern: "*.mzML"
  - log:
      type: file
      description: log file
      pattern: "*.log"
  - version:
      type: file
      description: File containing software version
      pattern: "versions.yml"
authors:
  - "@daichengxin"
