name: consensusid
description: Computes a consensus from results of multiple peptide identification engines.
keywords:
  - consensus scoring
  - peptide database search
  - OpenMS
tools:
  - ConsensusID:
      description: |
        Tool to Computes a consensus from results of multiple peptide identification engines.
      homepage: https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/TOPP_ConsensusID.html
      documentation: https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/TOPP_ConsensusID.html
input:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - id_file:
      type: file
      description: |
        Putative peptide-spectrum matches in idXML format (potentially multiple per spectrum). Score needs to be comparable (e.g. probability)
      pattern: "*.idXML"
output:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - id_files_idx_ForIDPEP_FDR:
      type: file
      description: |
        Identifications with annotated FDR.
      pattern: "*.idXML"
  - log:
      type: file
      description: log file
      pattern: "*.log"
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"
authors:
  - "@daichengxin"
