name: msrescore_features
description: A module to perform add features from MS2PIP and DeepLC
keywords:
  - MS2
  - rescoring
tools:
  - custom:
      description: |
        A custom module for MS2 rescoring.
      homepage: https://github.com/bigbio/quantms
      documentation: https://github.com/bigbio/quantms/tree/readthedocs
input:
  - idxml_file:
      type: file
      description: idXML identification file
      pattern: "*.idXML"
  - mzml:
      type: file
      description: spectrum data file
      pattern: "*.mzML"
  - meta:
      type: map
      description: Groovy Map containing sample information
output:
  - idxml:
      type: file
      description: idXML identification file after MS2 rescoring
      pattern: "*.idXML"
  - version:
      type: file
      description: File containing software version
      pattern: "versions.yml"
authors:
  - "@daichengxin"
