name: tdf2mzml
description: convert raw bruker files to mzml files
keywords:
  - raw
  - mzML
  - .d
tools:
  - tdf2mzml:
      description: |
        It takes a bruker .d raw file as input and outputs indexed mzML
      homepage: https://github.com/mafreitas/tdf2mzml
      documentation: https://github.com/mafreitas/tdf2mzml
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
  - rawfile:
      type: file
      description: |
        Bruker Raw file archived using tar
      pattern: "*.d.tar"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'MD5', enzyme:trypsin ]
  - mzml:
      type: file
      description: indexed mzML
      pattern: "*.mzML"
  - log:
      type: file
      description: log file
      pattern: "*.log"
  - version:
      type: file
      description: File containing software version
      pattern: "versions.yml"
authors:
  - "@jspaezp"
