name: sage
description: Peptide identification part of the Sage tool for MS analysis
keywords:
  - identification
  - OpenMS
  - sage
tools:
  - SageAdapter:
      description: |
        OpenMS adapter for the identification part of the Sage tool for MS analysis.
      homepage: https://abibuilder.cs.uni-tuebingen.de/archive/openms/Documentation/nightly/html/TOPP_SageAdapter.html
      documentation: https://abibuilder.cs.uni-tuebingen.de/archive/openms/Documentation/nightly/html/TOPP_SageAdapter.html
input:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - mzml_file:
      type: file
      description: Input spectrum data files.
      pattern: "*.mzML"
  - database:
      type: file
      description: fasta file
      pattern: "*.{fasta,fa}"
output:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - id_files_sage:
      type: file
      description: Output file
      pattern: "*.idXML"
  - log:
      type: file
      description: log file
      pattern: "*.log"
  - version:
      type: file
      description: File containing software version
      pattern: "versions.yml"
authors:
  - "@jpfeuffer"
