name: preliminary_analysis
description: A module for preliminary analysis of individual raw files with DIA-NN using the in-silico generated library (also from DIA-NN).
keywords:
  - DIA-NN
  - DIA
tools:
  - DIA-NN:
      description: |
        DIA-NN - a universal software for data-independent acquisition (DIA) proteomics data processing by Demichev.
      homepage: https://github.com/vdemichev/DiaNN
      documentation: https://github.com/vdemichev/DiaNN
input:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - predict_tsv:
      type: file
      description: Silico-predicted spectral library by deep leaning predictor in DIA-NN
      pattern: "*.tsv"
  - mzML:
      type: file
      description: Spectra file in mzML format
      pattern: "*.mzML"
output:
  - diann_quant:
      type: file
      description: Quantification file from DIA-NN
      pattern: "*.quant"
  - log:
      type: file
      description: DIA-NN log file
      pattern: "*_diann.log"
  - version:
      type: file
      description: File containing software version
      pattern: "versions.yml"
authors:
  - "@daichengxin"
