name: mzmlindexing
description: Converts mzML to indexed mzML
keywords:
  - raw
  - mzML
  - OpenMS
tools:
  - FileConverter:
      description: |
        Converts between different MS file formats
      homepage: http://www.openms.de/doxygen/nightly/html/TOPP_FileConverter.html
      documentation: http://www.openms.de/doxygen/nightly/html/TOPP_FileConverter.html
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
  - mzmlfile:
      type: file
      description: |
        Input file to convert.
      pattern: "*.mzML"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
  - mzmls_indexed:
      type: file
      description: indexed mzML file
      pattern: "*.mzML"
  - log:
      type: file
      description: log file
      pattern: "*.log"
  - version:
      type: file
      description: File containing software version
      pattern: "versions.yml"
authors:
  - "@daichengxin"
