name: luciphor
description: Modification site localisation using LuciPHOr2.
keywords:
  - LuciPHOr2
  - modification
  - OpenMS
tools:
  - LuciphorAdapter:
      description: |
        Calculates scores for the localization of variable modifications.
      homepage: https://abibuilder.cs.uni-tuebingen.de/archive/openms/Documentation/nightly/html/TOPP_LuciphorAdapter.html
      documentation: https://abibuilder.cs.uni-tuebingen.de/archive/openms/Documentation/nightly/html/TOPP_LuciphorAdapter.html
input:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - mzml_file:
      type: file
      description: Input spectrum file.
      pattern: "*.mzML"
  - id_file:
      type: file
      description: Protein/peptide identifications file
      pattern: "*.idXML"
output:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - out_id_ptmscores:
      type: file
      description: Protein/peptide identifications file. With scored potential modification sites
      pattern: "*.idXML"
  - log:
      type: file
      description: log file
      pattern: "*.log"
  - version:
      type: file
      description: File containing software version
      pattern: "versions.yml"
authors:
  - "@daichengxin"
