name: INDIVIDUAL_FINAL_ANALYSIS
description: A module for final analysis of individual raw files based on DIA-NN.
keywords:
  - DIA-NN
  - DIA
tools:
  - DIA-NN:
      description: |
        DIA-NN - a universal software for data-independent acquisition (DIA) proteomics data processing by Demichev.
      homepage: https://github.com/vdemichev/DiaNN
      documentation: https://github.com/vdemichev/DiaNN
input:
  - diann_log:
      type: file
      description: DIA-NN log file
      pattern: "assemble_empirical_library.log"
  - empirical_library:
      type: file
      description: An empirical spectral library from the .quant files.
      pattern: "empirical_library.tsv"
  - mzML:
      type: file
      description: Spectra file in mzML format
      pattern: "*.mzML"
  - fasta:
      type: file
      description: Protein sequence database in fasta format
      pattern: "*.{fasta,fa}"
output:
  - diann_quant:
      type: file
      description: Quantification file from DIA-NN
      pattern: "*.quant"
  - lib:
      type: file
      description: Spectral library file
      pattern: "*.tsv"
  - log:
      type: file
      description: DIA-NN log file
      pattern: "*_diann.log"
  - version:
      type: file
      description: File containing software version
      pattern: "versions.yml"
authors:
  - "@daichengxin"
